#! /bin/bash

function convert {
baza1=$1
liczba1=$2
declare -ia l1

l1=$liczba1

e=$(echo $l1 | sed 's/\(.\)/\1 /g')
l1=($e)

liczba2=0

cyfry=${#l1[@]}

for ((i=0; i<cyfry; i++)) do
liczba2=$(($(($liczba2*$baza1))+$((l1[$i]))));
done

convertResult=$liczba2
}

function drugaczesc {

baza2=$1
liczba2=$2
declare -ia l2

i=0
while [[ $liczba2 != 0 ]]
do
l2[$i]=$(($liczba2%$baza2))
liczba2=$(($liczba2/$baza2))
i=$(($i+1))
done

echo "WYNIK:"
for ((j=i-1; j>=0; j--))

do

if [[ $((l2[$j])) -ge 10 ]]
then
 case $((l2[$j]-10)) in
   (0) echo -n "A" ;;
   (1) echo -n "B" ;;
   (2) echo -n "C" ;;
   (3) echo -n "D" ;;
   (4) echo -n "E" ;;
   (5) echo -n "F" ;;
 esac

 else
 echo -n "$((l2[$j]))"
 fi

 done
 echo
 }

 echo "W jakim systemie jest zapisana Twoja liczba?"
 read  -e baza1
 echo -n "Podaj liczbe:"
 read  -e liczba1
 echo "Na jaki system chcesz ja zamienic?"
 read  -e baza2

 convert $baza1 $liczba1

 # zostala nadana wartosc zmiennej  convertResult

drugaczesc $baza2 $convertResult
